### PR TITLE
Changed router.navigate to call url.normalise with the lowercase flag set to false

### PR DESCRIPTION
**Pull request by srobertson421**
## Proposed changes
Fix for calling router.navigate and having the route params converted to lowercase

## Types of changes

What types of changes does your code introduce to Crayon?
_Put an `x` in the boxes that apply_

- [ x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by alshdavid** [comment]
Legend, thanks for that. I refactored the project when I noticed people contributing and I must have missed that. Appreciate your time.

**Comment by alshdavid** [comment]
I will increment the version shortly and publish this to npm

**Comment by alshdavid** [comment]
https://github.com/alshdavid/crayon/pull/41

**Comment by srobertson421** [comment]
@alshdavid Awesome thanks so much!

**Pull request merged**
