### PR TITLE
Parameter case sensitivity

### PR DESCRIPTION
**Pull request by rperki8**
## Proposed changes

The case of the req.params value will reflect the case specified in the url.

Example: 
```
pattern:  /user/:name
pathname: /user/Richard
current result:  { name: richard }
proposed result: { name: Richard }
```

## Types of changes

What types of changes does your code introduce to Crayon?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected) _marking as breaking change as it could break existing code if developer is expecting all req.params values to be lowercase_

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by srobertson421** [comment]
👍 Definitely need this merged! Thanks @rperki8

**Comment by alshdavid** [comment]
Hey nice PR! Thanks for your contribution. Looks good, happy to merge.

**Comment by alshdavid** [comment]
Oh, one thing first. Please update the `/router` package.json version to `3.0.0`

**Comment by alshdavid** [comment]
As a side note, I am working on making contributing easier. Right now it's pretty annoying to build/test the bits and pieces. The following branch aims to address that:

https://github.com/alshdavid/crayon/tree/upgrade/workspaces

**Pull request merged**
